version: "3.8"

services:
  mongodb:
    image: mongo:8.2
    container_name: sijawi-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sijawi
    restart: unless-stopped
    networks:
      - sijawi-network

  redis:
    image: redis:7-alpine
    container_name: sijawi-redis
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --protected-mode no
    restart: unless-stopped
    networks:
      - sijawi-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sijawi-web
    ports:
      - "3200:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sijawi
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - RUN_SEED=false
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - sijawi-network

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sijawi-email-worker
    command: pnpm run worker
    environment:
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=smtp.sumopod.com
      - SMTP_PORT=465
      - SMTP_USER=cmr984ap1el52qh08yjynbrsk
      - SMTP_PASS=IcblCdX00Ym1itPC7f6neJFnTVd2vhKD
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped
    networks:
      - sijawi-network

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sijawi-seed
    command:
      - npx
      - tsx
      - scripts/seed.ts
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sijawi
    depends_on:
      - mongodb
    networks:
      - sijawi-network
    profiles:
      - seed

volumes:
  mongodb_data:
    driver: local

networks:
  sijawi-network:
    driver: bridge